# Generated by Django 4.2.1 on 2023-09-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0002_accreditationbody_contactdetail_filedetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(default='City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='Country', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='pincode',
            field=models.CharField(default='531849', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.CharField(default='Country', max_length=100),
            preserve_default=False,
        ),
    ]
