# Generated by Django 3.2.7 on 2023-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0002_scholarship_db_student_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_addressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_address', models.CharField(max_length=50)),
                ('student_city', models.CharField(max_length=30)),
                ('student_state', models.CharField(max_length=30)),
                ('student_pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='student_contactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_phoneno', models.IntegerField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='student_personalDetails',
            fields=[
                ('student_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
                ('student_father', models.CharField(max_length=30)),
                ('student_mother', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='student_DB',
        ),
        migrations.AddField(
            model_name='student_contactdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarLink.student_personaldetails'),
        ),
        migrations.AddField(
            model_name='student_addressdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScholarLink.student_personaldetails'),
        ),
    ]
