# Generated by Django 3.2.7 on 2023-09-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0003_auto_20230907_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('student_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
                ('student_gender', models.CharField(max_length=20, null=True)),
                ('student_father', models.CharField(max_length=30)),
                ('student_mother', models.CharField(max_length=30)),
                ('student_phoneno', models.IntegerField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.CharField(max_length=50)),
                ('student_city', models.CharField(max_length=30)),
                ('student_state', models.CharField(max_length=30)),
                ('student_pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_contactdetails',
            name='student',
        ),
        migrations.DeleteModel(
            name='student_addressDetails',
        ),
        migrations.DeleteModel(
            name='student_contactDetails',
        ),
        migrations.DeleteModel(
            name='student_personalDetails',
        ),
    ]
