# Generated by Django 4.2.1 on 2023-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0004_remove_institution_abbreviation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='user',
            new_name='institute',
        ),
        migrations.AlterField(
            model_name='institutedoc',
            name='accredited_by',
            field=models.ManyToManyField(blank=True, related_name='authorized_institutions', to='ScholarLink.accreditationbody'),
        ),
        migrations.AlterField(
            model_name='institutedoc',
            name='scholarships_offered',
            field=models.ManyToManyField(blank=True, related_name='scholarship_institutions', to='ScholarLink.scholarship'),
        ),
    ]
