# Generated by Django 3.2.7 on 2023-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0004_remove_institution_abbreviation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='award_amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_specific',
            field=models.BooleanField(default=False),
        ),
    ]
