# Generated by Django 4.1.7 on 2023-09-13 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0005_rename_user_institution_institute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='institute',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='award_amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutedoc',
            name='accredited_by',
            field=models.ManyToManyField(related_name='authorized_institutions', to='ScholarLink.accreditationbody'),
        ),
        migrations.AlterField(
            model_name='institutedoc',
            name='scholarships_offered',
            field=models.ManyToManyField(related_name='scholarship_institutions', to='ScholarLink.scholarship'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
