# Generated by Django 4.1.7 on 2023-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0005_rename_user_institution_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='award_amount',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='state_specific',
            field=models.BooleanField(default=False),
        ),
    ]
