# Generated by Django 4.2.1 on 2023-10-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScholarLink', '0006_rename_institute_institution_user_and_more'),
        ('ScholarLink', '0007_student_is_verified_student_reason_student_status'),
    ]

    operations = [
    ]
